language: php

env:
  - SILEX_VERSION="2.0.*"

before_script:
  - composer require silex/silex:${SILEX_VERSION}
  - composer install --dev --prefer-source

script: vendor/bin/phpunit

php:
  - 5.5
  - 5.6
  - 7.0
